pipeline {
    agent any

    environment {
        IMAGE_NAME     = "frontend-jenkins-demo"
        CONTAINER_NAME = "frontend-demo"
        APP_PORT       = "8081"
        TRIVY_PATH     = "C:\\Users\\akalmoun\\Downloads\\trivy_0.68.2_windows-64bit\\trivy.exe"
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Build Docker Image') {
            steps {
                bat '''
                echo === Building Docker image ===
                cd application-frontend
                docker build -t %IMAGE_NAME%:latest .
                '''
            }
        }

        stage('Security Scan with Trivy') {
            steps {
                bat '''
                echo === Trivy security scan ===
                "%TRIVY_PATH%" image --severity HIGH,CRITICAL --exit-code 0 %IMAGE_NAME%:latest
                '''
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                echo === Deploying container ===
                docker rm -f %CONTAINER_NAME% >nul 2>&1 || exit 0
                docker run -d -p %APP_PORT%:80 --name %CONTAINER_NAME% %IMAGE_NAME%:latest
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline SUCCESS"
            echo "🌍 Application available at: http://localhost:8081"
        }
        failure {
            echo "❌ Pipeline FAILED"
        }
    }
}
